apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flagrant.litestreamConfigMapName" . }}
  labels:
    {{- include "flagrant.labels" . | nindent 4 }}
data:
  litestream.yml: |
    dbs:
      - path: {{ .Values.litestream.dbPath }}
        replicas:
          - type: s3
            bucket: {{ required "litestream.replica.bucket is required" .Values.litestream.replica.bucket | quote }}
            path: {{ .Values.litestream.replica.path | quote }}
            {{- if .Values.litestream.replica.region }}
            region: {{ .Values.litestream.replica.region | quote }}
            {{- end }}
            {{- if .Values.litestream.replica.endpoint }}
            endpoint: {{ .Values.litestream.replica.endpoint | quote }}
            {{- end }}
            force-path-style: {{ .Values.litestream.replica.forcePathStyle }}
