{{- if and (not .Values.litestream.s3.existingSecret) .Values.litestream.s3.accessKeyId .Values.litestream.s3.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flagrant.litestreamSecretName" . }}
  labels:
    {{- include "flagrant.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.litestream.s3.existingSecretAccessKeyIdKey }}: {{ .Values.litestream.s3.accessKeyId | quote }}
  {{ .Values.litestream.s3.existingSecretSecretAccessKeyKey }}: {{ .Values.litestream.s3.secretAccessKey | quote }}
{{- end }}
