[package]
name = "flagrant-types"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
regex = "1.10.4"
serde = {workspace = true}
serde_valid = {workspace = true}
sqlx = {workspace = true}

