[package]
name = "flagrant-api"
version.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
flagrant = {path = "../flagrant", version = "0.0.38"}
flagrant-types = {path = "../flagrant-types", version = "0.0.38"}
flagrant-proto = {path = "../flagrant-proto", version = "0.0.38", optional = true}

tokio = {workspace = true}
axum = {workspace = true}
axum-extra = {workspace = true}
sqlx = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
anyhow = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
thiserror = {workspace = true}
smallvec = {workspace = true}
toml = {workspace = true}
dotenvy = {workspace = true}
redis = {workspace = true, optional = true}
tonic = {workspace = true, optional = true}
tokio-stream = {workspace = true, optional = true}
prometheus = {workspace = true, optional = true}

utoipa = {workspace = true}
utoipa-scalar = {workspace = true}

[dependencies.tower-http]
version = "0.5.2"
features = ["add-extension", "compression-full", "trace"]

[features]
default = ["redis", "grpc", "metrics"]
redis = ["dep:redis"]
metrics = ["dep:prometheus"]
grpc = ["dep:tonic", "dep:tokio-stream", "dep:flagrant-proto"]

[[bin]]
name = "flagrant-api"
