use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::projects::list,
        crate::handlers::projects::fetch,
        crate::handlers::projects::create,
        crate::handlers::environments::list,
        crate::handlers::environments::fetch_by_id_or_name,
        crate::handlers::environments::create,
        crate::handlers::environments::update,
        crate::handlers::features::list,
        crate::handlers::features::fetch_by_id_or_name,
        crate::handlers::features::create,
        crate::handlers::features::delete,
        crate::handlers::features::clear_distribution,
        crate::handlers::features::get_rollout_status,
        crate::handlers::commit::apply,
        crate::handlers::snapshots::list,
        crate::handlers::snapshots::fetch,
        crate::handlers::snapshots::update_comment,
        crate::handlers::snapshots::restore,
        crate::handlers::variants::list,
        crate::handlers::variants::fetch,
        crate::handlers::variants::get_pinned_identities,
        crate::handlers::tags::list,
        crate::handlers::identities::list,
        crate::handlers::identities::fetch,
        crate::handlers::identities::create,
        crate::handlers::identities::delete,
        crate::handlers::identities::clear,
        crate::handlers::identities::get_variants,
        crate::handlers::traits::list,
        crate::handlers::traits::create,
        crate::handlers::traits::delete,
        crate::handlers::segments::list,
        crate::handlers::segments::create,
        crate::handlers::segments::fetch_by_id_or_name,
        crate::handlers::segments::get_overridden_features,
        crate::handlers::segments::get_feature_override_weights,
        crate::api::get_features,
        crate::handlers::admin::reload_config,
    ),
    components(
        schemas(
            flagrant_types::Project,
            flagrant_types::Environment,
            flagrant_types::Feature,
            flagrant_types::Variant,
            flagrant_types::VariantValue,
            flagrant_types::Tag,
            flagrant_types::TagList,
            flagrant_types::FeatureResponse,
            flagrant_types::Trait,
            flagrant_types::IdentityTrait,
            flagrant_types::IdentityVariant,
            flagrant_types::IdentityWithTraits,
            flagrant_types::payload::NewProjectPayload,
            flagrant_types::payload::ProjectCreatedResponse,
            flagrant_types::payload::NewEnvironmentPayload,
            flagrant_types::payload::UpdateEnvironmentPayload,
            flagrant_types::payload::NewFeaturePayload,
            flagrant_types::payload::FeaturePatch,
            flagrant_types::payload::VariantPatchOp,
            flagrant_types::payload::NewTraitPayload,
            flagrant_types::payload::IdentityTraitPayload,
            flagrant_types::payload::NewIdentityPayload,
            flagrant_types::payload::TraitPatchOp,
            flagrant_types::payload::IdentityPatch,
            flagrant_types::payload::IdentityOverridePatch,
            flagrant_types::Segment,
            flagrant_types::SegmentGroup,
            flagrant_types::SegmentRule,
            flagrant_types::Subject,
            flagrant_types::Comparator,
            flagrant_types::GroupConnector,
            flagrant_types::payload::NewSegmentPayload,
            flagrant_types::payload::SegmentPatch,
            flagrant_types::payload::SegmentPatchOp,
            flagrant_types::payload::SegmentVariantWeight,
            flagrant_types::SegmentFeatureOverride,
            flagrant_types::OverriddenVariant,
            flagrant_types::payload::CommitPayload,
            flagrant_types::payload::CommitResult,
            flagrant_types::payload::FeatureCommitPart,
            flagrant_types::payload::IdentityCommitPart,
            flagrant_types::payload::SegmentCommitPart,
            flagrant_types::payload::RestoreRequest,
            flagrant_types::payload::UpdateSnapshotCommentPayload,
            flagrant_types::Snapshot,
            flagrant_types::SnapshotState,
            flagrant_types::SnapshotVariant,
            flagrant_types::SnapshotSegmentOverride,
            flagrant_types::SnapshotSegmentGroup,
            flagrant_types::SnapshotIdentityOverride,
            flagrant_types::RolloutConfig,
            flagrant_types::RolloutStep,
            flagrant_types::RolloutStatus,
            flagrant_types::payload::RolloutPatchOp,
        )
    ),
    tags(
        (name = "projects", description = "Project management"),
        (name = "environments", description = "Environment management"),
        (name = "features", description = "Feature flag management"),
        (name = "variants", description = "Feature variant management"),
        (name = "tags", description = "Tag management"),
        (name = "identities", description = "Identity management"),
        (name = "traits", description = "Trait management"),
        (name = "segments", description = "Segment management"),
        (name = "commit", description = "Unified atomic commit operation"),
        (name = "snapshots", description = "Feature snapshot history and restore"),
        (name = "api", description = "Public client API"),
        (name = "admin", description = "Server administration"),
    ),
    info(
        title = "Flagrant API",
        version = "0.0.22",
        description = "CLI-powered feature-flagging service"
    )
)]
pub struct ApiDoc;
