use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::projects::list,
        crate::handlers::projects::fetch,
        crate::handlers::projects::create,
        crate::handlers::environments::list,
        crate::handlers::environments::fetch_by_id_or_name,
        crate::handlers::environments::create,
        crate::handlers::features::list,
        crate::handlers::features::fetch_by_id_or_name,
        crate::handlers::features::create,
        crate::handlers::features::update,
        crate::handlers::features::delete,
        crate::handlers::features::patch,
        crate::handlers::features::clear_distribution,
        crate::handlers::variants::list,
        crate::handlers::variants::fetch,
        crate::handlers::variants::create,
        crate::handlers::variants::update,
        crate::handlers::variants::delete,
        crate::handlers::tags::list,
        crate::handlers::identities::list,
        crate::handlers::identities::fetch,
        crate::handlers::identities::create,
        crate::handlers::identities::update,
        crate::handlers::identities::delete,
        crate::handlers::identities::clear,
        crate::handlers::identities::get_variants,
        crate::handlers::traits::list,
        crate::handlers::traits::create,
        crate::handlers::traits::delete,
        crate::handlers::segments::list,
        crate::handlers::segments::create,
        crate::handlers::segments::fetch_by_id_or_name,
        crate::handlers::segments::update,
        crate::handlers::segments::delete,
        crate::handlers::segments::add_group,
        crate::handlers::segments::delete_group,
        crate::handlers::segments::add_rule,
        crate::handlers::segments::delete_rule,
        crate::api::get_features,
    ),
    components(
        schemas(
            flagrant_types::Project,
            flagrant_types::Environment,
            flagrant_types::Feature,
            flagrant_types::Variant,
            flagrant_types::FeatureValue,
            flagrant_types::Tag,
            flagrant_types::TagList,
            flagrant_types::FeatureResponse,
            flagrant_types::Trait,
            flagrant_types::IdentityTrait,
            flagrant_types::IdentityVariant,
            flagrant_types::IdentityWithTraits,
            flagrant_types::payload::NewProjectPayload,
            flagrant_types::payload::ProjectCreatedResponse,
            flagrant_types::payload::NewEnvironmentPayload,
            flagrant_types::payload::NewFeaturePayload,
            flagrant_types::payload::NewVariantPayload,
            flagrant_types::payload::FeaturePatch,
            flagrant_types::payload::VariantPatchOp,
            flagrant_types::payload::NewTraitPayload,
            flagrant_types::payload::IdentityTraitPayload,
            flagrant_types::payload::NewIdentityPayload,
            flagrant_types::payload::TraitPatchOp,
            flagrant_types::payload::IdentityPatch,
            flagrant_types::payload::IdentityOverridePatch,
            flagrant_types::Segment,
            flagrant_types::SegmentGroup,
            flagrant_types::SegmentRule,
            flagrant_types::SegmentDriver,
            flagrant_types::Comparator,
            flagrant_types::GroupConnector,
            flagrant_types::payload::NewSegmentPayload,
            flagrant_types::payload::NewGroupPayload,
            flagrant_types::payload::NewRulePayload,
        )
    ),
    tags(
        (name = "projects", description = "Project management"),
        (name = "environments", description = "Environment management"),
        (name = "features", description = "Feature flag management"),
        (name = "variants", description = "Feature variant management"),
        (name = "tags", description = "Tag management"),
        (name = "identities", description = "Identity management"),
        (name = "traits", description = "Trait management"),
        (name = "segments", description = "Segment management"),
        (name = "api", description = "Public client API"),
    ),
    info(
        title = "Flagrant API",
        version = "0.0.10",
        description = "CLI-powered feature-flagging service"
    )
)]
pub struct ApiDoc;
