[package]
name = "flagrant-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
flagrant= {path = "../flagrant"}

# common dependencies
tokio = {workspace = true}
axum = {workspace = true}
axum-extra = {workspace = true}
tower = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}
serde_json = {workspace = true}
thiserror = {workspace = true}
anyhow = {workspace = true}

clap = {version = "4.5.1"}

[dependencies.tower-http]
version = "*"
features = ["add-extension", "compression-full", "trace"]
