[package]
name = "flagrant-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
flagrant-repl = {path = "../flagrant-repl"}
flagrant-types = {path = "../flagrant-types"}
flagrant-client = {path = "../flagrant-client", features = ["blocking"]}

# common dependencies
serde = {workspace = true}
serde_json = {workspace = true}
anyhow = {workspace = true}
reqwest = {workspace = true, features = ["json", "blocking"]}
rustyline = { workspace = true }
fancy-table = "0.4.3"
argh = "0.1"
strum = {workspace = true}
strum_macros = {workspace = true}
colored = "3.0.0"
tempfile = "3"

[[bin]]
name = "flagrant-cli"
