[package]
name = "flagrant-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
flagrant= {path = "../flagrant"}

# common dependencies
tokio = {workspace = true, features = ["macros"]}
tracing = {workspace = true}
tracing-log = {workspace = true}
tracing-subscriber = {workspace = true, features = ["env-filter"]}
serde_json = {workspace = true}
thiserror = {workspace = true}
anyhow = {workspace = true}

axum = {version = "0.7"}
axum-extra = {version = "0.9.1", features = ["typed-header"]}
tower = {version = "0.4.13", features = ["util", "timeout", "load-shed", "limit"]}
clap = {version = "4.5.1"}

[dependencies.tower-http]
version = "*"
features = ["add-extension", "compression-full", "trace"]
