[package]
name = "flagrant-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
flagrant = {path = "../flagrant"}
flagrant-api = {path = "../flagrant-api"}
flagrant-types = {path = "../flagrant-types"}

# common dependencies
serde = {workspace = true}
anyhow = {workspace = true}
reqwest = {workspace = true, features = ["json", "blocking"]}
rustyline = {version = "14.0.0", features = ["derive"]}

clap = {version = "4.5.1"}

[[bin]]
name = "flagrant-cli"
